apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trading
resources:
- deployment.yaml
- service.yaml
images:
- name: ghcr.io/nedcius/trading-platform-frontend
  newName: ghcr.io/nedcius/trading-platform-frontend
  newTag: sha-35639be
